//LOGIN & LOGOUT
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
//USERS
export const USERS_LOADING = 'USERS_LOADING';
export const USERS_SUCCESS = 'USERS_SUCCESS';
export const USERS_FAILED = 'USERS_FAILED';
//SINGLE USER
export const USER_LOADING = 'USER_LOADING';
export const USER_SUCCESS = 'USER_SUCCESS';
//FLASH MESSAGE
export const FLASHMESSAGE_SUCCESS = 'FLASHMESSAGE_SUCCESS';
export const FLASHMESSAGE_FAILURE = 'FLASHMESSAGE_FAILURE';
export const FLASHMESSAGE_RESET = 'FLASHMESSAGE_RESET';